#!/bin/bash

function install() {

    if [ "$EUID" -ne 0 ]
    then echo -e "\e[31mPermission denied: try sudo"
    exit
    fi

    echo -e "\e[32mInstalling..."
    config="/etc/scantekctl"
    opt="/opt/scantekctl"
    mods="/opt/scantekctl/modules"
    bin="/usr/bin/scantekctl"

    g++ ./src/*.cpp -o ./bin/scantekctl -I ./inc/ `pkg-config --cflags --libs opencv`
    [[ $? -eq 0 ]] || {
        echo -e "\e[31mCompilation error"
        exit 1
    }

    [[ ! -d $config ]] && mkdir $config; [[ ! -d $opt ]] && mkdir $opt; [[ ! -d $mods ]] && mkdir $mods
    cp "$(pwd)/bin/scantekctl" $opt
    ([[ -f $bin ]] && echo -e "\e[31mAlready installed.") || \
    (ln -s $opt/scantekctl $bin 2>/dev/null && echo -e "\e[32mSuccess!!")
}

install