#!/bin/bash

echo "Decompressing Scantek CLI.."
export TMPDIR=`mktemp -d /tmp/selfextract.XXXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xzv -C $TMPDIR

CDIR=`pwd`
cd $TMPDIR

echo "Installing Scantek CLI.."
./install

cd $CDIR
rm -rf $TMPDIR

exit 0

__ARCHIVE_BELOW__
